name: Java Maven Build, Test, and SonarCloud Analysis

on:
  push:
    branches:
      - "feature/lab3"
  pull_request:
    branches:
      - "feature/lab3"

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
  test_and_sonarcloud:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: Execute JUnit Tests and Gather Code Coverage Data
      run: mvn clean test jacoco:report --file pom.xml
    - name: Upload Code Coverage to SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        organization: <your-sonarcloud-organization-key>
        project: <your-sonarcloud-project-key>
        token: ${{ secrets.SONAR_TOKEN }}
